title: iOS Development Blogs
description: iOS Development blogs hosted on GitHub Pages
author: Rakesh Khandagale
theme: minima

# Navigation links
minima:
  social_links:
    - platform: github
      user_url: https://github.com/khandagalerakesh

  # Add this section for header navigation
  header_pages:
    - about.md